---
# CI code for testing SaltStack Netdata scripts
name: SaltStack
on:
  push:
    branches:
      - develop

jobs:
  Test:
    name: Test Salt
    runs-on: macos-10.15
    strategy:
      matrix:
        image:
          - 'ubuntu2004'
          - 'centos7'
          - 'centos8'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create ${{ matrix.image }}
        run: |
          vagrant up ${{ matrix.image }}
      - name: Cleanup
        if: always()
        run: |
          vagrant destroy ${{ matrix.image }} -f
